FROM node:lts-alpine

ENV LOCAL /app
RUN mkdir -p ${LOCAL}
WORKDIR ${LOCAL}

COPY package*.json ${LOCAL}/
RUN npm install -g @vue/cli --silent
RUN npm install --silent

COPY . ${LOCAL}/
RUN npm run build

RUN rm -rf /node_modules /src /public
RUN npm install express compression serve-static connect-history-api-fallback

EXPOSE 5000

CMD [ "npm", "start" ]