version: '3.7'

services:
  development:
    build: 
      context: .
      dockerfile: Dockerfile.development
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    command: [ "npm", "run", "serve" ]
  production:
    build: 
      context: .
      dockerfile: Dockerfile.production
    working_dir: /usr/src/app
    env_file: 
      - .env.production.local
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: [ "node", "server.js" ]
