version: '3.7'

services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:8080
    command: [ "npm", "run", "serve" ]
  prd:
    build: 
      context: .
      dockerfile: Dockerfile.prd
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
    command: [ "node", "server.js" ]
