FROM node:lts-alpine

ENV LOCAL /app
ENV VUE_APP_API_PLACES https://test-frontend-developer.s3.amazonaws.com/data/locations.json
RUN mkdir -p ${LOCAL}
WORKDIR ${LOCAL}

COPY package*.json ${LOCAL}/
RUN npm install -g @vue/cli --silent
RUN npm install --silent

COPY . ${LOCAL}/
RUN npm run build

RUN rm -rf /node_modules /src /public
RUN npm install express compression serve-static connect-history-api-fallback

EXPOSE $PORT

CMD [ "npm", "start" ]